services:
  postgres:
    image: postgres:17
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./internal/repository/postgres/init_db:/docker-entrypoint-initdb.d
      - api_db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  migrations:
    image: migrate/migrate
    container_name: migrations
    hostname: migrations
    volumes:
      - ./internal/repository/postgres/migrations:/migrations
    depends_on:
     - postgres
    restart: "no"
volumes:
  api_db-data: