CREATE TABLE users(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE ,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE articles(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    user_id INTEGER NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    content VARCHAR,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
